# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d34e2b8c2378d833def94bb6840d8fb9ce10f43c73e1b00593bbcf68b1706a4217a74399e9c7c3f476f507af77ea79167e199110eeaefce19905afaf4826659

test:
  secret_key_base: 4803979f3255dc62aff470ed8a614cd7f389eaefa947e550cb9b0aaaf953e2b67569409e329aabfc458866b1a1db41d203fefb941fe25c3ca25196f5b488cab8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
